# Use the official MySQL 5.7 image as the base image
FROM mysql:5.7

# Set the environment variables for MySQL
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
# Expose the MySQL port
EXPOSE 3306
